import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property<int> counter: 42;
    callback request-increase-value();
    VerticalBox {
        Text {
            text: @tr("Counter: {}", root.counter);
        }
        Button {
            text: @tr("Increase value");
            clicked => {
                root.request-increase-value();
            }
        }
     }
}
